const MENU_DATA = [
  // ===== PIZZA =====
  {cat:"pizza",name:"Margarita",desc:"Tomato sauce, cheese",price:"330 / 370",icon:"🍕"},
  {cat:"pizza",name:"Napolitana",desc:"Tomato sauce, cheese, mushrooms",price:"350 / 400",icon:"🍕"},
  {cat:"pizza",name:"Cardinale",desc:"Tomato sauce, cheese, chicken ham",price:"350 / 400",icon:"🍕"},
  {cat:"pizza",name:"Mafiosi",desc:"Tomato sauce, cheese, smoked meat, mushrooms",price:"370 / 430",icon:"🍕"},
  {cat:"pizza",name:"Vegetaria",desc:"Tomato sauce, cheese, mushrooms, onion, peppers",price:"370 / 430",icon:"🌿"},
  {cat:"pizza",name:"Bolognese",desc:"Tomato sauce, cheese, minced meat, egg",price:"370 / 430",icon:"🍕"},
  {cat:"pizza",name:"Capriciosa",desc:"Tomato sauce, cheese, chicken ham, mushrooms",price:"370 / 420",icon:"🍕",badge:"Popular"},
  {cat:"pizza",name:"Istanbul",desc:"Tomato sauce, cheese, chicken ham, mushrooms, egg, sour cream",price:"400 / 450",icon:"🍕"},
  {cat:"pizza",name:"Oriental",desc:"Tomato sauce, cheese, beef pepperoni, minced meat",price:"370 / 430",icon:"🍕"},
  {cat:"pizza",name:"Quattro Stagioni",desc:"Tomato sauce, cheese, smoked meat, mushrooms, tuna, onion",price:"400 / 450",icon:"🍕"},
  {cat:"pizza",name:"Americano Special",desc:"Tomato sauce, cheese, chicken ham, mushrooms, smoked meat, olive, chicken breast",price:"420 / 470",icon:"⭐",badge:"House Special"},
  {cat:"pizza",name:"Tonno",desc:"Tomato sauce, cheese, tuna, onion",price:"400 / 450",icon:"🐟"},
  {cat:"pizza",name:"Frutti di Mare",desc:"Tomato sauce, cheese, sea food",price:"600 / 750",icon:"🦐",badge:"Premium"},
  {cat:"pizza",name:"Hawaii",desc:"Tomato sauce, cheese, chicken ham, pineapple",price:"470 / 550",icon:"🍍"},
  {cat:"pizza",name:"Chicken",desc:"Tomato sauce, cheese, chicken breast",price:"400 / 450",icon:"🍗"},
  {cat:"pizza",name:"Chicken Mix",desc:"Tomato sauce, cheese, chicken breast mix",price:"400 / 450",icon:"🍗"},
  {cat:"pizza",name:"Quattro Formaggi",desc:"Tomato sauce, 4 types of cheese",price:"400 / 450",icon:"🧀"},
  {cat:"pizza",name:"Pepperoni",desc:"Tomato sauce, cheese, sugjuk",price:"400 / 450",icon:"🍕"},
  {cat:"pizza",name:"Pizza Salad",desc:"Tomato sauce, cheese, salad",price:"450 / 550",icon:"🥗"},

  // ===== PASTA =====
  {cat:"pasta",name:"Spaghetti Marinara",desc:"Tomato sauce",price:"370",icon:"🍝"},
  {cat:"pasta",name:"Spaghetti Bologneze",desc:"Minced meat",price:"430",icon:"🍝"},
  {cat:"pasta",name:"Spaghetti Prima Vera",desc:"Vegetable sauce",price:"430",icon:"🌿"},
  {cat:"pasta",name:"Spaghetti Frutti Di Mare",desc:"Marinare sauce, sea food",price:"730",icon:"🦐",badge:"Premium"},
  {cat:"pasta",name:"Spaghetti Alfredo",desc:"Cream sauce with chicken",price:"500",icon:"🍝"},
  {cat:"pasta",name:"Spaghetti Carbonara",desc:"Cream sauce with ham",price:"450",icon:"🍝"},
  {cat:"pasta",name:"Makaroni Bolognese",desc:"Minced meat",price:"430",icon:"🍝"},
  {cat:"pasta",name:"Makaroni Vodka Sauce",desc:"Tomato sauce, double cream",price:"450",icon:"🍝"},
  {cat:"pasta",name:"Makaroni Zingara",desc:"Marinare sauce, mushrooms, olives, chilli peppers, tomato",price:"450",icon:"🌶️"},
  {cat:"pasta",name:"Baked Ziti",desc:"Pasta with tomato, white cheese, cheese",price:"430",icon:"🧀"},
  {cat:"pasta",name:"Lasagne Bologneze",desc:"Bolognese sauce, sour cream, cheese",price:"430",icon:"🍝"},
  {cat:"pasta",name:"Spaghetti with Shrimps",desc:"Shrimps, pasta",price:"1000",icon:"🦐",badge:"Premium"},

  // ===== GRILL / SKARA =====
  {cat:"grill",name:"Kebabs",desc:"Traditional grilled kebabs",price:"400",icon:"🥩"},
  {cat:"grill",name:"Kebabs with Cheese Oven Baked",desc:"Kebabs with kashkaval, oven baked",price:"450",icon:"🥩"},
  {cat:"grill",name:"Burger with Cheese",desc:"Burger with cheese",price:"500",icon:"🍔"},
  {cat:"grill",name:"Meat Rolls with Curd Cheese",desc:"Grilled rolls with kajmak",price:"470",icon:"🥩"},
  {cat:"grill",name:"Chicken Steak with Garnish",desc:"Chicken steak with garnish",price:"470",icon:"🍗"},
  {cat:"grill",name:"Chicken Steak with White Sauce",desc:"Chicken steak with white sauce",price:"500",icon:"🍗"},
  {cat:"grill",name:"Chicken Schnitzel with Fries",desc:"Chicken schnitzel with fries",price:"500",icon:"🍗"},
  {cat:"grill",name:"Chicken Parmesan",desc:"Chicken steak with sauce and macaroni",price:"500",icon:"🍗"},
  {cat:"grill",name:"Chicken Marsala",desc:"Chicken with mushrooms sauce, vegetables",price:"800",icon:"🍗",badge:"Premium"},
  {cat:"grill",name:"Chicken Franchese",desc:"Chicken with lemon sauce",price:"800",icon:"🍗",badge:"Premium"},
  {cat:"grill",name:"Mixed Grill",desc:"Assorted grilled meats",price:"900",icon:"🔥",badge:"For Sharing"},
  {cat:"grill",name:"Lamb Oven Baked",desc:"Slow-roasted lamb",price:"1000",icon:"🐑",badge:"Premium"},

  // ===== BREAKFAST / APPETIZERS =====
  {cat:"breakfast",name:"Omelette",desc:"Chicken ham, smoked meat, cheese",price:"280",icon:"🥚"},
  {cat:"breakfast",name:"Fried Eggs",desc:"Eggs fried to order",price:"300",icon:"🍳"},
  {cat:"breakfast",name:"Grilled Mushrooms",desc:"Mushrooms on the grill",price:"300",icon:"🍄"},
  {cat:"breakfast",name:"Roasted Mushrooms",desc:"Pan-roasted mushrooms",price:"350",icon:"🍄"},
  {cat:"breakfast",name:"French Fries",desc:"Crispy golden fries",price:"200",icon:"🍟"},
  {cat:"breakfast",name:"French Fries with Cheese",desc:"Fries with white cheese",price:"250",icon:"🍟"},
  {cat:"breakfast",name:"Bread Sticks",desc:"Freshly baked bread sticks",price:"100",icon:"🥖"},

  // ===== SALADS =====
  {cat:"salads",name:"Shopska Salad",desc:"Tomato, cucumber, white cheese",price:"220",icon:"🥗"},
  {cat:"salads",name:"Greek Salad",desc:"Tomato, cucumber, white cheese, onion",price:"250",icon:"🥗"},
  {cat:"salads",name:"Village Salad",desc:"Tomato, cucumber, pepper, lettuce, onion",price:"300",icon:"🥗"},
  {cat:"salads",name:"Tuna Salad",desc:"Tuna, tomato, cucumber, lettuce, onion",price:"450",icon:"🐟"},
  {cat:"salads",name:"Caesar Salad",desc:"Classic Caesar",price:"450",icon:"🥗"},
  {cat:"salads",name:"Americano Salad",desc:"Mixed vegetables",price:"350",icon:"🥗"},
  {cat:"salads",name:"Bruschetta",desc:"Toasted bread with toppings",price:"350",icon:"🍞"},

  // ===== DRINKS =====
  {cat:"drinks",name:"Coca Cola",desc:"0.25L",price:"120",icon:"🥤"},
  {cat:"drinks",name:"Fanta",desc:"0.25L",price:"120",icon:"🥤"},
  {cat:"drinks",name:"Sprite",desc:"0.25L",price:"120",icon:"🥤"},
  {cat:"drinks",name:"Schweppes",desc:"0.25L",price:"120",icon:"🥤"},
  {cat:"drinks",name:"Pelisterka",desc:"0.25L / 0.75L",price:"80 / 180",icon:"💧"},
  {cat:"drinks",name:"Rosa Mineral Water",desc:"0.25L / 0.75L",price:"80 / 180",icon:"💧"},
  {cat:"drinks",name:"Red Bull",desc:"0.25L",price:"250",icon:"🥫"},
  {cat:"drinks",name:"Jaffa Juice",desc:"0.20L",price:"120",icon:"🧃"},
  {cat:"drinks",name:"Skopsko",desc:"Beer · 0.33L",price:"180",icon:"🍺"},
  {cat:"drinks",name:"Zlaten Dab",desc:"Beer · 0.33L",price:"200",icon:"🍺"},
  {cat:"drinks",name:"Heineken",desc:"Beer · 0.25L",price:"200",icon:"🍺"},
  {cat:"drinks",name:"Tuborg",desc:"Beer · 0.33L",price:"200",icon:"🍺"},
  {cat:"drinks",name:"Corona",desc:"Beer · 0.33L",price:"300",icon:"🍺"},
  {cat:"drinks",name:"Alexandria Wine",desc:"0.187L / 0.75L",price:"280 / 800",icon:"🍷"},
  {cat:"drinks",name:"Glass Wine",desc:"0.2L",price:"250",icon:"🍷"},
  {cat:"drinks",name:"Lozova Rakia",desc:"0.05L",price:"120",icon:"🥃"},
  {cat:"drinks",name:"Mastika",desc:"0.05L",price:"120",icon:"🥃"},
  {cat:"drinks",name:"Vodka",desc:"0.05L",price:"120",icon:"🥃"},
  {cat:"drinks",name:"Ouzo",desc:"0.05L",price:"120",icon:"🥃"},
  {cat:"drinks",name:"Cognac",desc:"0.05L",price:"120",icon:"🥃"},
  {cat:"drinks",name:"Whiskey",desc:"0.05L",price:"350",icon:"🥃"},
  {cat:"drinks",name:"Pelinkovac",desc:"0.05L",price:"120",icon:"🥃"},
  {cat:"drinks",name:"Gin",desc:"0.05L",price:"150",icon:"🥃"},
  {cat:"drinks",name:"Espresso",desc:"Coffee",price:"70",icon:"☕"},
  {cat:"drinks",name:"Macchiato",desc:"Coffee",price:"70",icon:"☕"},
  {cat:"drinks",name:"Cappuccino",desc:"Coffee",price:"150",icon:"☕"},
  {cat:"drinks",name:"Nescafe",desc:"Coffee",price:"150",icon:"☕"},
  {cat:"drinks",name:"Tea",desc:"Hot tea",price:"70",icon:"🍵"},
];
